using System.Text.Json.Serialization;

namespace AdvanclySDK;

public class InitiateLoanApplicationRequest
{
    /// <summary>
    /// The last name of the borrower.
    /// </summary>
    [JsonPropertyName("last_name")]
    public string LastName { get; set; }

    /// <summary>
    /// The first name of the borrower.
    /// </summary>
    [JsonPropertyName("first_name")]
    public string FirstName { get; set; }

    /// <summary>
    /// The name of the borrower's bank account. This is required only for non Nigerian aggregators.
    /// </summary>
    [JsonPropertyName("bank_account_name")]
    public string BankAccountName { get; set; }

    /// <summary>
    /// This is the unique valid identification number of the borrower used to perform KYC.
    /// </summary>
    [JsonPropertyName("identity_number")]
    public string IdentityNumber { get; set; }

    /// <summary>
    /// The base 64 image of the borrower or the url of the uploaded image.
    /// </summary>
    [JsonPropertyName("photo_url")]
    public string PhotoUrl { get; set; }

    /// <summary>
    /// The gender of the borrower should either be male or female.
    /// </summary>
    [JsonPropertyName("gender")]
    public string Gender { get; set; }

    /// <summary>
    /// The borrower's phone number.
    /// </summary>
    [JsonPropertyName("phone_number")]
    public string PhoneNumber { get; set; }

    /// <summary>
    /// The borrower's email.
    /// </summary>
    [JsonPropertyName("email")]
    public string Email { get; set; }

    /// <summary>
    /// The name of the company being registered for corporate borrower.
    /// </summary>
    [JsonPropertyName("company_name")]
    public string CompanyName { get; set; }

    /// <summary>
    /// The type of borrower to be onboarded. 1 for individual and 2 for corporate.
    /// </summary>
    [JsonPropertyName("borrower_type")]
    public int BorrowerType { get; set; }

    /// <summary>
    /// Borrower's date of birth in the format yyyy-MM-dd
    /// </summary>
    [JsonPropertyName("date_of_birth")]
    public string DateOfBirth { get; set; }

    /// <summary>
    /// State of the borrower. To view list of states under an aggregator see Get Country's States endpoint.
    /// </summary>
    [JsonPropertyName("state")]
    public string State { get; set; }

    /// <summary>
    /// City of the borrower.
    /// </summary>
    [JsonPropertyName("city")]
    public string City { get; set; }

    /// <summary>
    /// Address of the borrower.
    /// </summary>
    [JsonPropertyName("residence_address")]
    public string ResidenceAddress { get; set; }

    /// <summary>
    /// City where the company is located for the corporate borrower.
    /// </summary>
    [JsonPropertyName("company_city")]
    public string CompanyCity { get; set; }

    /// <summary>
    /// Company address for corporate borrower.
    /// </summary>
    [JsonPropertyName("company_address")]
    public string CompanyAddress { get; set; }

    /// <summary>
    /// Company's business registration number for the corporate borrower.
    /// </summary>
    [JsonPropertyName("registration_number")]
    public string RegistrationNumber { get; set; }

    /// <summary>
    /// Certified country code is entered here such as "NG" (Nigeria), "GH" (Ghana), "SA" (South Africa)
    /// </summary>
    [JsonPropertyName("country_code")]
    public string CountryCode { get; set; }

    /// <summary>
    /// The sector code of the borrower applying for the loan. To view all sectors and their sector codes, see the Get Sectors endpoint.
    /// </summary>
    [JsonPropertyName("sector_code")]
    public string SectorCode { get; set; }

    /// <summary>
    /// The Id of the product from which the loan is being requested. To view, all the products for a particular aggregator see the Get Aggregator Product endpoint.
    /// </summary>
    [JsonPropertyName("product_id")]
    public int ProductId { get; set; }

    /// <summary>
    /// The unique loan reference for the aggregator. This will be generated by the client.
    /// </summary>
    [JsonPropertyName("aggregator_loan_ref")]
    public string AggregatorLoanRef { get; set; }

    /// <summary>
    /// The bank code of the borrower's bank. To view, all banks and their bank codes see the Get Country's Bank List endpoint.
    /// </summary>
    [JsonPropertyName("bank_code")]
    public string BankCode { get; set; }

    /// <summary>
    /// The bank account number of the borrower.
    /// </summary>
    [JsonPropertyName("bank_account_num")]
    public string BankAccountNum { get; set; }

    /// <summary>
    /// State where the company is located for the corporate borrower. To view all states for an aggregator nationality, see Get Country's State endpoint.
    /// </summary>
    [JsonPropertyName("company_state")]
    public string CompanyState { get; set; }

    /// <summary>
    /// This indicates if a wallet is to be created for a borrower or not (true or false).
    /// </summary>
    [JsonPropertyName("create_wallet")]
    public bool? CreateWallet { get; set; }

    /// <summary>
    /// The customer's job category.
    /// </summary>
    [JsonPropertyName("customer_category")]
    public string CustomerCategory { get; set; }

    /// <summary>
    /// The reason for which the loan is created.
    /// </summary>
    [JsonPropertyName("loan_purpose")]
    public string LoanPurpose { get; set; }

    /// <summary>
    /// The loan interest rate. If the interest rate is zero, the loan product's interest rate will be used.
    /// </summary>
    [JsonPropertyName("annual_interest_rate")]
    public string AnnualInterestRate { get; set; }

    /// <summary>
    /// The amount to be loaned out.
    /// </summary>
    [JsonPropertyName("loan_amount")]
    public decimal LoanAmount { get; set; }

    /// <summary>
    /// The duration of the loan is in months.
    /// </summary>
    [JsonPropertyName("loan_tenure")]
    public int LoanTenure { get; set; }
}